#cloud-config

preserve_hostname: false

fqdn: ${fqdn}

manage_etc_hosts: true

users:
  - name: rocky
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}
chpasswd:
  list:
    - rocky:rocky # this format <username>:<password>
  expire: False